# Generated by Django 2.0.3 on 2018-03-15 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('timezone', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('logpath', models.CharField(default='/opt/fr.krus/acct/', max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logparser.City')),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Dim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Internet on BRAS', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RadiusAttributeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RadiusAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='none', max_length=200)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logparser.RadiusAttributeType')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=200)),
                ('ssh_username', models.CharField(max_length=20)),
                ('ssh_key', models.CharField(default='../key', max_length=200)),
                ('radius_log_path', models.CharField(default='../radius-logs', max_length=200)),
                ('tmp_path', models.CharField(default='../tmp', max_length=200)),
                ('log_path', models.CharField(default='../log', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logparser.Collector')),
            ],
        ),
        migrations.CreateModel(
            name='TrafficSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TrafficType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=200)),
                ('type_id', models.CharField(default='none', max_length=200)),
                ('parser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logparser.Parser')),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=50)),
                ('from_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('to_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('filename', models.FileField(blank=True, upload_to='uploads/')),
                ('author', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logparser.City')),
                ('parser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logparser.Parser')),
            ],
        ),
        migrations.AddField(
            model_name='trafficsummary',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logparser.TrafficType'),
        ),
        migrations.AddField(
            model_name='trafficsummary',
            name='parser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logparser.Parser'),
        ),
        migrations.AddField(
            model_name='index',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logparser.RadiusAttributeType'),
        ),
        migrations.AddField(
            model_name='index',
            name='parser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logparser.Parser'),
        ),
        migrations.AddField(
            model_name='dim',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logparser.RadiusAttributeType'),
        ),
        migrations.AddField(
            model_name='dim',
            name='parser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logparser.Parser'),
        ),
        migrations.AddField(
            model_name='counter',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logparser.RadiusAttributeType'),
        ),
        migrations.AddField(
            model_name='counter',
            name='parser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logparser.Parser'),
        ),
    ]
