# Generated by Django 2.0.3 on 2018-03-15 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logparser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='filename',
        ),
    ]
