# Generated by Django 2.0.3 on 2018-03-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logparser', '0002_remove_userrequest_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='filename',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
