# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logparser', '0003_userrequest_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128)),
                ('job_id', models.CharField(max_length=128)),
                ('result', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='filename',
            field=models.FileField(blank=True, upload_to='user_media'),
        ),
    ]
