# Generated by Django 2.0.3 on 2018-03-18 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logparser', '0003_userrequest_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiusattributetype',
            name='parser',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='logparser.Parser'),
        ),
        migrations.AddField(
            model_name='radiusattributevalue',
            name='parser',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='logparser.Parser'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='filename',
            field=models.FileField(blank=True, upload_to='user_media'),
        ),
    ]
