# Generated by Django 2.0.3 on 2018-03-18 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logparser', '0004_auto_20180318_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiusattributetype',
            name='parser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='logparser.Parser'),
        ),
        migrations.AlterField(
            model_name='radiusattributevalue',
            name='parser',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='logparser.Parser'),
        ),
    ]
