# Generated by Django 2.0.3 on 2018-03-28 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logparser', '0004_auto_20180321_0627'),
        ('logparser', '0006_auto_20180318_1639'),
    ]

    operations = [
    ]
