# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logparser', '0007_merge_20180329_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='job_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='test_url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
