# Generated by Django 2.0.3 on 2018-04-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logparser', '0008_auto_20180410_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='log_path',
            field=models.CharField(default='./log', max_length=200),
        ),
        migrations.AlterField(
            model_name='settings',
            name='radius_log_path',
            field=models.CharField(default='./radius-logs', max_length=200),
        ),
        migrations.AlterField(
            model_name='settings',
            name='ssh_key',
            field=models.CharField(default='./key', max_length=200),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tmp_path',
            field=models.CharField(default='./tmp', max_length=200),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
