# Generated by Django 2.0.3 on 2018-04-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logparser', '0009_auto_20180414_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='result',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='test_url',
        ),
    ]
