# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-14 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logparser', '0010_auto_20180414_1829'),
        ('logparser', '0009_userrequest_result'),
    ]

    operations = [
    ]
